class SpecialConditions:
    agony: bool
    burning: bool
    bleeding: bool
    cursed: bool
    dazzled: bool
    drowning: bool
    drunk: bool
    electrified: bool
    freezing: bool
    hungry: bool
    logoutBlack: bool
    poisoned: bool
    protectionZoneBlock: bool
    slowed: bool
